esp32:
  board: esp32dev
  framework:
    type: esp-idf

output:
  - platform: ledc
    id: pwm_red_output
    pin: ${red_led_pin}
    frequency: 500 Hz
    inverted: false
    max_power: 0.40 # Current limits do not increase
  - platform: ledc
    id: pwm_green_output
    pin: ${green_led_pin}
    frequency: 500 Hz
    inverted: false
    max_power: 0.40 # Current limits do not increase

number:
  - platform: template
    name: "Stop Distance Threshold"
    id: stop_distance_threshold
    min_value: 0.1
    max_value: 4.0
    step: 0.05
    restore_value: true
    initial_value: 0.8
    unit_of_measurement: "m"
    optimistic: true

light:
  - platform: monochromatic
    name: "Stop Light"
    output: pwm_red_output
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: "Go Light"
    output: pwm_green_output
    restore_mode: ALWAYS_ON

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: "IP Address"

sensor:
  - platform: ultrasonic
    id: hc_sr04_1
    trigger_pin: ${hc_sr04_trig_pin}
    echo_pin: ${hc_sr04_echo_pin}
    update_interval: 200ms
    internal: true        # Keep data local
    on_value:
      then:
        - lambda: |-
            static float last_good = -1;
            float dist = id(hc_sr04_1).state;
            float stop_thresh = id(stop_distance_threshold).state;

            // Reject invalid readings
            if (dist <= .12|| (dist > stop_thresh + 0.15) ) {
              id(pwm_red_output).set_level(0.0);
              id(pwm_green_output).set_level(0.4);
              return;
            }

            // LED logic
            if (dist <= stop_thresh) {
              id(pwm_red_output).set_level(0.4);
              id(pwm_green_output).set_level(0.0);
            } else {
              id(pwm_red_output).set_level(0.0);
              id(pwm_green_output).set_level(0.4);
            }
  - platform: template
    name: Vehicle Distance
    id: hc_sr04_1_ha
    unit_of_measurement: "M"
    accuracy_decimals: 2
    update_interval: 2s
    lambda: |-
      return id(hc_sr04_1).state;   // read internal sensor

status_led:
  pin: ${status_led_pin}
